vm:
  name: ANSIBLE-ASADA31
  size: "Standard_D2_v3"

ip_configuration:
  - name: ""
    subnet_id: ""
    private_ip_address_allocation: "Dynamic"

image_reference: 
  publisher: "MicrosoftWindowsServer"
  offer: "WindowsServer"
  sku: "2022-Datacenter"
  version: "latest"